name: sillog
description: Treering sillog

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 0.1.1+4

environment:
  sdk: '>=2.12.0 < 3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  kakao_flutter_sdk: ^0.8.2
  dio: ^4.0.0
  json_annotation:
  # shared_preferences: ^2.0.8
  platform:
  package_info:
  intl: ^0.17.0
  image_picker: ^0.8.2
  flutter_image_compress: ^1.0.0
  timeline_list: ^0.0.3
  syncfusion_flutter_datepicker: ^19.2.55
  http: ^0.13.3
  timelines: ^0.1.0
  flutter_screenutil: ^5.0.0
  get: ^4.3.8
  path_provider: ^2.0.2
  sliding_up_panel: ^2.0.0
  card_swiper: ^1.0.4
  flutter_typeahead: ^3.2.0
  font_awesome_flutter: ^9.1.0
  google_sign_in: ^5.2.1
  firebase_core: ^1.10.0
  firebase_auth: ^3.2.0
  scroll_navigation: ^1.3.2
  dotted_border: ^2.0.0+1
  file_picker: ^4.0.0
  thumbnailer: ^2.0.0
  flutter_keyboard_visibility: ^5.0.3
  share: ^2.0.4
  get_it: ^7.1.3
  rxdart: ^0.27.2
  moor: ^4.5.0
  sqlite3_flutter_libs: ^0.5.0
  filesize: ^2.0.1
  share_plus: ^3.0.4
  modal_bottom_sheet: 2.0.0
  flutter_native_splash:

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  flutter_pdfview: ^1.2.1
  flutter_spinkit: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  build_runner:
  moor_generator:

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/login/
    - assets/sticker/
    - assets/image/
    - assets/image/file_logo/
    - assets/image/nav_icon/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    #   - family: Schyler
    #     fonts:
    #       - asset: fonts/Schyler-Regular.ttf
    #       - asset: fonts/Schyler-Italic.ttf
    #         style: italic
    - family: NotoSans
      fonts:
        - asset: assets/fonts/NotoSans-Regular.ttf
        - asset: assets/fonts/NotoSans-Bold.ttf
          weight: 700

    - family: Inqlipquid
      fonts:
        - asset: assets/fonts/Inklipquid.otf

    - family: Cafe24Shiningstar
      fonts:
        - asset: assets/fonts/Cafe24Shiningstar.ttf

    - family: SpoqaHanSansNeo
      fonts:
        - asset: assets/fonts/SpoqaHanSansNeo-Thin.otf
          weight: 200
        - asset: assets/fonts/SpoqaHanSansNeo-Light.otf
          weight: 300
        - asset: assets/fonts/SpoqaHanSansNeo-Medium.otf
          weight: 500
        - asset: assets/fonts/SpoqaHanSansNeo-Regular.otf
          weight: 400
        - asset: assets/fonts/SpoqaHanSansNeo-Bold.otf
          weight: 700

    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Thin.ttf
          weight: 200
        - asset: assets/fonts/Roboto-Light.ttf
          weight: 300
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto-Regular.ttf
          weight: 400
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

flutter_native_splash:
  color: '#FFFFFF'
  image: assets/image/sillog_logo.png
